name: New Issue
description: Description
title: "[Create New Issue]: "
labels: ["GSSoC22"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make an issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a brief description
      placeholder: Please include a summary. Please also include relevant motivation and context.
      value: "Description"
    validations:
      required: true
